#!/bin/bash
cd C:\Users\Administrator\Desktop\GitHub\ipa
del *.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/431_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/421_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/411_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/403_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/402_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/401_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/400_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/380-b2_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/380-b1_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/363_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/362_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/361_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/356_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/352_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/342_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/351_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/340_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/350_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/338_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/310_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/103_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/104_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/105_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/107_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/108_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/109_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/110_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/120_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/122_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/123_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/124_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/125_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/126_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/127_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/128_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/129_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/130_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/133_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/134_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/136_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/137_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/138_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/139_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/140_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/doubleH3lix_doubleH3lix.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/Pangu_Pangu.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/yalu_yalu102.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/32_h3lix.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/11.0-11.41_Electra.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/doubleH3lix_doubleH3lix.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/3.0_Th0r.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/007_Meridian.ipa
del *.1
cd C:\Users\Administrator\Desktop\lanzous
del *.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/431_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/421_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/411_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/403_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/402_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/401_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/400_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/380-b2_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/380-b1_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/363_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/362_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/361_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/356_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/352_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/342_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/351_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/340_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/350_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/338_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/310_unc0ver.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/127_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/140_Chimera.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/doubleH3lix_doubleH3lix.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/Pangu_Pangu.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/yalu_yalu102.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/32_h3lix.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/11.0-11.41_Electra.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/doubleH3lix_doubleH3lix.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/3.0_Th0r.ipa
wget http://ipawj.nuosike.cn/ipa/YYlIl-lIl/007_Meridian.ipa
del *.1
echo "批量下载成功！"
