cd C:\Users\Administrator\Desktop\ipa\ipa
del *.ipa
del *.1
del *.crdownload
echo "批量删除成功！"
wget http://ipa.iwba.cn/yy/431_unc0ver.ipa
wget http://ipa.iwba.cn/yy/421_unc0ver.ipa
wget http://ipa.iwba.cn/yy/411_unc0ver.ipa
wget http://ipa.iwba.cn/yy/403_unc0ver.ipa
wget http://ipa.iwba.cn/yy/402_unc0ver.ipa
wget http://ipa.iwba.cn/yy/401_unc0ver.ipa
wget http://ipa.iwba.cn/yy/400_unc0ver.ipa
wget http://ipa.iwba.cn/yy/380-b2_unc0ver.ipa
wget http://ipa.iwba.cn/yy/380-b1_unc0ver.ipa
wget http://ipa.iwba.cn/yy/363_unc0ver.ipa
wget http://ipa.iwba.cn/yy/362_unc0ver.ipa
wget http://ipa.iwba.cn/yy/361_unc0ver.ipa
wget http://ipa.iwba.cn/yy/356_unc0ver.ipa
wget http://ipa.iwba.cn/yy/352_unc0ver.ipa
wget http://ipa.iwba.cn/yy/342_unc0ver.ipa
wget http://ipa.iwba.cn/yy/351_unc0ver.ipa
wget http://ipa.iwba.cn/yy/340_unc0ver.ipa
wget http://ipa.iwba.cn/yy/350_unc0ver.ipa
wget http://ipa.iwba.cn/yy/338_unc0ver.ipa
wget http://ipa.iwba.cn/yy/310_unc0ver.ipa
wget http://ipa.iwba.cn/yy/103_Chimera.ipa
wget http://ipa.iwba.cn/yy/104_Chimera.ipa
wget http://ipa.iwba.cn/yy/105_Chimera.ipa
wget http://ipa.iwba.cn/yy/107_Chimera.ipa
wget http://ipa.iwba.cn/yy/108_Chimera.ipa
wget http://ipa.iwba.cn/yy/109_Chimera.ipa
wget http://ipa.iwba.cn/yy/110_Chimera.ipa
wget http://ipa.iwba.cn/yy/120_Chimera.ipa
wget http://ipa.iwba.cn/yy/122_Chimera.ipa
wget http://ipa.iwba.cn/yy/123_Chimera.ipa
wget http://ipa.iwba.cn/yy/124_Chimera.ipa
wget http://ipa.iwba.cn/yy/125_Chimera.ipa
wget http://ipa.iwba.cn/yy/126_Chimera.ipa
wget http://ipa.iwba.cn/yy/127_Chimera.ipa
wget http://ipa.iwba.cn/yy/128_Chimera.ipa
wget http://ipa.iwba.cn/yy/129_Chimera.ipa
wget http://ipa.iwba.cn/yy/130_Chimera.ipa
wget http://ipa.iwba.cn/yy/133_Chimera.ipa
wget http://ipa.iwba.cn/yy/134_Chimera.ipa
wget http://ipa.iwba.cn/yy/136_Chimera.ipa
wget http://ipa.iwba.cn/yy/137_Chimera.ipa
wget http://ipa.iwba.cn/yy/138_Chimera.ipa
wget http://ipa.iwba.cn/yy/139_Chimera.ipa
wget http://ipa.iwba.cn/yy/140_Chimera.ipa
wget http://ipa.iwba.cn/yy/doubleH3lix_doubleH3lix.ipa
wget http://ipa.iwba.cn/yy/Pangu_Pangu.ipa
wget http://ipa.iwba.cn/yy/yalu_yalu102.ipa
wget http://ipa.iwba.cn/yy/32_h3lix.ipa
wget http://ipa.iwba.cn/yy/11.0-11.41_Electra.ipa
wget http://ipa.iwba.cn/yy/doubleH3lix_doubleH3lix.ipa
wget http://ipa.iwba.cn/yy/3.0_Th0r.ipa
wget http://ipa.iwba.cn/yy/Meridian_Meridian.ipa
del *.1
cd C:\Users\Administrator\Desktop\ipa\ipa蓝奏云
del *.ipa
del *.1
del *.crdownload
echo "批量删除成功！"
wget http://ipa.iwba.cn/yy/431_unc0ver.ipa
wget http://ipa.iwba.cn/yy/421_unc0ver.ipa
wget http://ipa.iwba.cn/yy/411_unc0ver.ipa
wget http://ipa.iwba.cn/yy/403_unc0ver.ipa
wget http://ipa.iwba.cn/yy/402_unc0ver.ipa
wget http://ipa.iwba.cn/yy/401_unc0ver.ipa
wget http://ipa.iwba.cn/yy/400_unc0ver.ipa
wget http://ipa.iwba.cn/yy/380-b2_unc0ver.ipa
wget http://ipa.iwba.cn/yy/380-b1_unc0ver.ipa
wget http://ipa.iwba.cn/yy/363_unc0ver.ipa
wget http://ipa.iwba.cn/yy/362_unc0ver.ipa
wget http://ipa.iwba.cn/yy/361_unc0ver.ipa
wget http://ipa.iwba.cn/yy/356_unc0ver.ipa
wget http://ipa.iwba.cn/yy/352_unc0ver.ipa
wget http://ipa.iwba.cn/yy/342_unc0ver.ipa
wget http://ipa.iwba.cn/yy/351_unc0ver.ipa
wget http://ipa.iwba.cn/yy/340_unc0ver.ipa
wget http://ipa.iwba.cn/yy/350_unc0ver.ipa
wget http://ipa.iwba.cn/yy/338_unc0ver.ipa
wget http://ipa.iwba.cn/yy/310_unc0ver.ipa
wget http://ipa.iwba.cn/yy/140_Chimera.ipa
wget http://ipa.iwba.cn/yy/doubleH3lix_doubleH3lix.ipa
wget http://ipa.iwba.cn/yy/Pangu_Pangu.ipa
wget http://ipa.iwba.cn/yy/yalu_yalu102.ipa
wget http://ipa.iwba.cn/yy/32_h3lix.ipa
wget http://ipa.iwba.cn/yy/11.0-11.41_Electra.ipa
wget http://ipa.iwba.cn/yy/doubleH3lix_doubleH3lix.ipa
wget http://ipa.iwba.cn/yy/3.0_Th0r.ipa
wget http://ipa.iwba.cn/yy/Meridian_Meridian.ipa
del *.1
echo "批量下载成功！"